-- Script pour créer ou corriger la table photos avec support multi-utilisateurs pour les likes

-- 1. Créer la table photos si elle n'existe pas
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  media_type text not null check (media_type in ('photo', 'video')),
  likes integer default 0,
  liked_by text[] default '{}', -- Tableau de texte pour stocker les emails des utilisateurs
  created_by text
);

-- 2. Si la table existe déjà, vérifier et ajouter les colonnes manquantes
-- Ajouter la colonne liked_by si elle n'existe pas
do $$ 
begin
  if not exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' 
    and table_name = 'photos' 
    and column_name = 'liked_by'
  ) then
    alter table public.photos add column liked_by text[] default '{}';
  end if;
end $$;

-- Ajouter la colonne created_by si elle n'existe pas
do $$ 
begin
  if not exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' 
    and table_name = 'photos' 
    and column_name = 'created_by'
  ) then
    alter table public.photos add column created_by text;
  end if;
end $$;

-- 3. Corriger les données existantes : s'assurer que liked_by est un tableau vide si null
update public.photos 
set liked_by = '{}' 
where liked_by is null;

-- 4. Corriger les données existantes : s'assurer que likes correspond au nombre d'éléments dans liked_by
update public.photos 
set likes = coalesce(array_length(liked_by, 1), 0);

-- 5. Enable Row Level Security (RLS) - optionnel mais recommandé
alter table public.photos enable row level security;

-- 6. Créer une politique pour permettre à tout le monde de lire les photos
drop policy if exists "Enable read access for all users" on public.photos;
create policy "Enable read access for all users"
on public.photos
for select
to public
using (true);

-- 7. Créer une politique pour permettre à tout le monde d'insérer des photos
drop policy if exists "Enable insert access for all users" on public.photos;
create policy "Enable insert access for all users"
on public.photos
for insert
to public
with check (true);

-- 8. Créer une politique pour permettre à tout le monde de mettre à jour les likes
drop policy if exists "Enable update access for all users" on public.photos;
create policy "Enable update access for all users"
on public.photos
for update
to public
using (true)
with check (true);

-- 9. Créer une politique pour permettre à tout le monde de supprimer des photos
drop policy if exists "Enable delete access for all users" on public.photos;
create policy "Enable delete access for all users"
on public.photos
for delete
to public
using (true);

-- 10. Afficher la structure de la table pour vérification
select 
  column_name, 
  data_type, 
  column_default,
  is_nullable
from information_schema.columns
where table_schema = 'public' 
  and table_name = 'photos'
order by ordinal_position;
