-- ATTENTION : Ce script supprime la table photos et la recrée complètement
-- Toutes les photos seront perdues !
-- N'exécutez ce script que si vous êtes sûr de vouloir tout recommencer

-- 1. Supprimer la table existante
DROP TABLE IF EXISTS public.photos CASCADE;

-- 2. Recréer la table avec la bonne structure
CREATE TABLE public.photos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  image_url text NOT NULL,
  media_type text NOT NULL CHECK (media_type IN ('photo', 'video')),
  likes integer DEFAULT 0,
  liked_by text[] DEFAULT '{}', -- TABLEAU de texte pour stocker les emails
  created_by text
);

-- 3. Activer RLS
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;

-- 4. Créer les politiques
CREATE POLICY "Enable read access for all users"
ON public.photos FOR SELECT TO public USING (true);

CREATE POLICY "Enable insert access for all users"
ON public.photos FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Enable update access for all users"
ON public.photos FOR UPDATE TO public USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete access for all users"
ON public.photos FOR DELETE TO public USING (true);

-- 5. Vérifier la structure
SELECT 
  column_name, 
  data_type, 
  column_default,
  is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND table_name = 'photos'
ORDER BY ordinal_position;
