-- Create the PlanningEvent table based on the JSON schema
create table public."PlanningEvent" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  time text not null, -- Format HH:MM
  description text,
  "order" integer, -- Quoted because order is a reserved keyword
  started boolean default false
);

-- Enable Row Level Security (RLS)
alter table public."PlanningEvent" enable row level security;

-- Create policy to allow everyone to read events
create policy "Enable read access for all users"
on public."PlanningEvent"
for select
to public
using (true);

-- Create policy to allow authenticated users (or admins) to update 'started' status
-- specific access control depends on your auth setup, allowing public read is usually safe for this.

-- Insert some default data (The 'Mock' data we used)
insert into public."PlanningEvent" (title, time, description, "order", started)
values
  ('Cérémonie Civile', '14:00', 'Mairie de Paris', 1, true),
  ('Séance Photo', '15:30', 'Parc des Buttes-Chaumont', 2, true),
  ('Vin d''Honneur', '17:00', 'Cocktail & Petits fours', 3, false),
  ('Dîner Gastronomique', '20:00', 'Grand Salon', 4, false),
  ('Ouverture du bal', '23:00', 'Première danse des mariés', 5, false),
  ('Gâteau', '23:30', 'Découpe de la pièce montée', 6, false);
